[package]
name = "capnp-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.14.9"
capnpc = "0.14.9"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
glob = "0.3.0"
clap = { version = "4.0.14", features = ["derive"] }
