name: build

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build Target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../capnp-parse-${{ matrix.target }}.tar.gz capnp-parse
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'capnp-parse*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}